export const BANKS_LIST = [
  { code: "044", name: "Access Bank" },
  { code: "050", name: "Ecobank Nigeria" },
  { code: "070", name: "Fidelity Bank" },
  { code: "011", name: "First Bank of Nigeria" },
  { code: "058", name: "Guaranty Trust Bank (GTBank)" },
  { code: "030", name: "Heritage Bank" },
  { code: "082", name: "Keystone Bank (Now Polaris)" },
  { code: "221", name: "Stanbic IBTC Bank" },
  { code: "232", name: "Sterling Bank" },
  { code: "032", name: "Union Bank of Nigeria" },
  { code: "033", name: "United Bank for Africa (UBA)" },
  { code: "215", name: "Unity Bank" },
  { code: "035", name: "Wema Bank" },
  { code: "057", name: "Zenith Bank" },
  { code: "076", name: "Polaris Bank" },
  { code: "101", name: "Providus Bank" },
  { code: "060", name: "Ecobank" },
  { code: "040", name: "First City Monument Bank (FCMB)" },
  { code: "100004", name: "OPay" },
  { code: "999991", name: "PalmPay" },
  { code: "100002", name: "Moniepoint" },
  { code: "090114", name: "Kuda Bank" },
  { code: "090536", name: "VFD Microfinance Bank" },
  { code: "090560", name: "Migo" },
  { code: "090591", name: "Fairmoney Microfinance Bank" },
  { code: "090534", name: "Carbon" },
  { code: "090400", name: "Renmoney" },
];